docker-compose-yaml: docker-compose.yml

project: tyler-example

environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
