<?php

/**
 * @file
 * Contains drupalconvienna.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupalconvienna_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupalconvienna module.
    case 'help.page.drupalconvienna':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DrupalCon Vienna') . '</p>';
      return $output;

    default:
  }
}
